field_map_1 = {
    "reportTitle": "[name='title']",
    "valuationPurpose": "[name='purpose_id']",
    "valuePremise": "[name='value_premise_id']",
    "valueBase": "[name='value_base_id']",
    "reportType": "[name='report_type']",
    "valuationDate": "[name='valued_at']",
    "reportIssuingDate": "[name='submitted_at']",
    "assumptions": "[name='assumptions']",
    "specialAssumptions": "[name='special_assumptions']",
    "finalValue": "[name='value']",
    "valuationCurrency": "[name='currency_id']",
    "reportAssetFile": "[name='report_file']",
    "clientName": "[name='client[0][name]']",
    "telephoneNumber": "[name='client[0][telephone]']",
    "emailAddress": "[name='client[0][email]']",
    "hasOtherUsers": "[name='has_user']",
    "valuerName": "[name='valuer[0][id]']",
    "contributionPercentage": "[name='valuer[0][contribution]']",
}

field_types_1 = {
    "reportTitle": "text",
    "valuationPurpose": "select",
    "valuePremise": "select",
    "valueBase": "select",
    "reportType": "radio",
    "valuationDate": "text",
    "reportIssuingDate": "text",
    "assumptions": "text",
    "specialAssumptions": "text",
    "finalValue": "text",
    "valuationCurrency": "select",
    "reportAssetFile": "file",
    "clientName": "text",
    "telephoneNumber": "text",
    "emailAddress": "text",
    "hasOtherUsers": "checkbox",
    "valuerName": "select",
    "contributionPercentage": "select",
}

field_map_2 = {
    "assetType": "[name='asset_type_id']",
    "inspectionDate": "[name='inspected_at']",
    "finalValue": "[name='value']",
    "marketApproach": "[id='approach1']",
    "comparableTransactionsMethod": "[name='approach[1][method][1][value]']",
    "incomeApproach": "[id='approach2']",
    "profitMethod": "[name='approach[2][method][5][value]']",
    "costApproach": "[id='approach3']",
    "summationMethod": "[name='approach[3][method][11][value]']",
    "country": "[name='country_id'] + .select2-container .select2-selection",
    "region": "[name='region_id'] + .select2-container .select2-selection",
    "city": "[name='city_id'] + .select2-container .select2-selection",
    "longitude": "[name='longitude']",
    "latitude": "[name='latitude']",
    "assetUsageSector": "[name='asset_usage_id']",
}

field_types_2 = {
    "assetType": "dynamic_select",
    "inspectionDate": "text",
    "finalValue": "text",
    "marketApproach": "select",
    "comparableTransactionsMethod": "text",
    "incomeApproach": "select",
    "profitMethod": "text",
    "costApproach": "select",
    "summationMethod": "text",
    "country": "location",
    "region": "location",
    "city": "location",
    "longitude": "text",
    "latitude": "text",
    "assetUsageSector": "dynamic_select",
}

field_map_3 = {
    "blockNumber": "[name='attribute[1]']",
    "propertyNumber": "[name='attribute[2]']",
    "certificateNumber": "[name='attribute[3]']",
    "ownershipType": "[name='attribute[4]']",
    "ownershipPercentage": "[name='attribute[5]']",
    "rentalDuration": "[name='attribute[6]']",
    "rentalEndDate": "[name='attribute[7]']",
    "streetFacingFronts": "[name='attribute[8]']",
    "distanceFromCityCenter": "[name='attribute[9]']",
    "facilities": "[name='attribute[10][]']",
    "landArea": "[name='attribute[11]']",
    "buildingArea": "[name='attribute[12]']",
    "authorizedLandCoverPercentage": "[name='attribute[13]']",
    "authorizedHeight": "[name='attribute[14]']",
    "landLeased": "[id='15']",
    "buildingStatus": "[name='attribute[16]']",
    "finishingStatus": "[name='attribute[17]']",
    "furnishingStatus": "[name='attribute[18]']",
    "airConditioning": "[name='attribute[19]']",
    "buildingType": "[name='attribute[20]']",
    "otherFeatures": "[name='attribute[21][]']",
    "bestUse": "[name='attribute[27]']",
    "assetAge": "[name='attribute[28]']",
    "streetWidth": "[name='attribute[31]']",
}

field_types_3 = {
    "blockNumber": "text",
    "propertyNumber": "text",
    "certificateNumber": "text",
    "ownershipType": "select",
    "ownershipPercentage": "text",
    "rentalDuration": "text",
    "rentalEndDate": "text",
    "streetFacingFronts": "select",
    "distanceFromCityCenter": "text",
    "facilities": "checkbox",
    "landArea": "text",
    "buildingArea": "text",
    "authorizedLandCoverPercentage": "text",
    "authorizedHeight": "text",
    "landLeased": "radio",

    "buildingStatus": "select",
    "finishingStatus": "select",
    "furnishingStatus": "select",
    "airConditioning": "select",
    "buildingType": "select",

    "otherFeatures": "checkbox",
    "bestUse": "radio",
    "assetAge": "text",
    "streetWidth": "text"
}


form_steps = [
    {"field_map": field_map_1, "field_types": field_types_1},
    {"field_map": field_map_2, "field_types": field_types_2},
    {"field_map": field_map_3, "field_types": field_types_3},
]